spring:
  neo4j:
    uri: neo4j+s://76024857.databases.neo4j.io
    username: neo4j
    password: 8l56AjoxsV-pOPVbCHpnoj76WHG1oeEyMDHoHiMwG10
  security:
    jwt:
      secret: 729a616ce4a17f8b7dd522a228b4c712335e8374e8e95deaef309d4fbeb69cf2
      expiration: 86400000
